# render.yaml
services:
  - type: web
    name: your-bun-backend
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true