services:
  - type: web
    name: blog-aggregator-backend
    env: docker
    docker:
      dockerfile: ./backend/Dockerfile
      dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free
    numInstances: 1
    healthCheckPath: /health
    autoDeploy: true